tenant: tyvdh
app: turing-signing-server
service: turing-signing-server-${opt:i}

plugins:
  - serverless-iam-roles-per-function
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

package:
  individually: true

custom:
  webpack:
    webpackConfig: webpack.config.js
    keepOutputDirectory: true
    includeModules:
      forceInclude:
        - source-map-support
    packager: npm

  serverless-offline:
    useChildProcesses: true
    httpsProtocol: certs
    httpPort: 400${opt:i}
    lambdaPort: 300${opt:i}

  serverless-iam-roles-per-function:
    defaultInherit: true

  customDomain:
    domainName: turing-signing-server-${opt:i}.stellar.buzz
    certificateName: turing-signing-server-${opt:i}.stellar.buzz
    createRoute53Record: false

provider:
  name: aws
  environment:
    SERVICE_NAME: turing-signing-server-${opt:i}
    PG_DATABASE: turing-signing-server-${opt:i}
    AWS_BUCKET_NAME: turing-signing-server-${opt:i}
    i: ${opt:i}
  runtime: nodejs12.x
  region: us-east-1
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTelemetryRecords
        - xray:PutTraceSegments
      Resource: '*'

functions:
  uploadContract:
    handler: src/uploadContract.default
    environment: ${file(env.yml)}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObject
          - s3:PutObject
          - s3:PutObjectAcl
          - s3:PutObjectTagging
        Resource: arn:aws:s3:::turing-signing-server-${opt:i}/*
    timeout: 9
    maximumRetryAttempts: 0
    maximumRecordAgeInSeconds: 0
    reservedConcurrency: 6
    events:
      - http:
          path: contract
          method: POST
          cors:
            origin: '*'
            cacheControl: 'public; max-age=14400'

  updateContract:
    handler: src/updateContract.default
    environment: ${file(env.yml)}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:DeleteObjectTagging
          - s3:PutObjectTagging
        Resource: arn:aws:s3:::turing-signing-server-${opt:i}/*
    timeout: 6
    maximumRetryAttempts: 0
    maximumRecordAgeInSeconds: 0
    reservedConcurrency: 6
    events:
      - http:
          path: contract/{hash}
          method: PUT
          cors:
            origin: '*'
            cacheControl: 'public; max-age=14400'

  getContract:
    handler: src/getContract.default
    environment: ${file(env.yml)}
    iamRoleStatements: []
    timeout: 3
    maximumRetryAttempts: 0
    maximumRecordAgeInSeconds: 0
    events:
      - http:
          path: contract/{hash}
          method: GET
          cors:
            origin: '*'
            cacheControl: 'public; max-age=14400'

  runContract:
    handler: src/runContract.default
    environment: ${file(env.yml)}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObjectTagging
        Resource: arn:aws:s3:::turing-signing-server-${opt:i}/*
      - Effect: Allow
        Action:
          - lambda:InvokeFunction
        Resource: '*'
    timeout: 9
    reservedConcurrency: 9
    maximumRetryAttempts: 0
    maximumRecordAgeInSeconds: 0
    events:
      - http:
          path: contract/{hash}/run
          method: POST
          cors:
            origin: '*'
            cacheControl: 'public; max-age=14400'

  runContractCollate:
    handler: src/runContractCollate.default
    environment: ${file(env.yml)}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObjectTagging
        Resource: arn:aws:s3:::turing-signing-server-${opt:i}/*
    timeout: 12
    maximumRetryAttempts: 0
    maximumRecordAgeInSeconds: 0
    events:
      - http:
          path: contract/{hash}/run/collate
          method: POST
          cors:
            origin: '*'
            cacheControl: 'public; max-age=14400'

  runContractPrivate:
    handler: src/runContractPrivate.default
    iamRoleStatements: []
    maximumRetryAttempts: 0
    maximumRecordAgeInSeconds: 0
    memorySize: 128
    timeout: 6

  checkContractPrivate:
    handler: src/checkContractPrivate.default
    environment: ${file(env.yml)}
    iamRoleStatements: []
    maximumRetryAttempts: 0
    maximumRecordAgeInSeconds: 0
    timeout: 6