[TSS]
TURRETS=[
  'GCQIG3PL446FRQUPURVJ3L3MIAB62YPSNWB7PNU72EUOASYS3FDM6VPY',
  'GCC63HKFK2NGRPB6GWGDGCPAU3XG5E545O32G3VGTYX2O73QIKB7NZ5Z',
  'GDFXSY7WAMLUABSPTFDG7KJVUDM2DMJXO6OGEIBQYRLWKHW2DTFBWBPL',
  'GDWWCJLFOSWHBLGWIYECP4ZJECNTMW2VMWV3C5T733KVFQQRE57CFZKD',
  'GCBUD7XJUSMAACYIVF7ZGXFMJGTSUHS446NBZZAXPI365UQDEMXXUHXF'
]